apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: frontend-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  matchLabels:
    app: frontend-deployment
  metadata:
    labels:
      app: frontend-deployment
  selector: null
  spec:
    containers:
    - image: foo/bar:3.7
      name: app
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  template: null
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-deployment-hpa
spec:
  maxReplicas: 5
  metrics:
  - type: Resource
  minReplicas: 1
  resource:
    name: cpu
    target:
      averageUtilization: 50
      type: Utilization
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
